apiVersion: v2
name: prometheus-stack
description: Prometheus observabilidade stack
type: application
version: 1.0.0
appVersion: "0.85.0"

dependencies:
  - name: kube-prometheus
    version: 11.3.10
    repository: https://charts.bitnami.com/bitnami