apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: memory-nodes-alerts
  namespace: observabilidade
  labels:
    release: prometheus
spec:
  groups:
    - name: memory-nodes-alerts
      rules:
        - alert: HighMemoryUsage
          expr: >
            (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 7
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Memória alta na instância {{ $labels.instance }}"
            description: "Instância {{ $labels.instance }} usando {{ printf \"%.2f\" $value }}% da memória"
            impact: "Possível OOM (Out of Memory) e crash de aplicações"
            action: "Identificar processos com alto uso de memória ou adicionar mais RAM"